config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy' 

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

	root to: 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update], param: :reset_token
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if logged_in?
  		@micropost = current_user.microposts.build
  		@feed_items = current_user.feed.paginate(page: params[:page])
  	end
  end

  def help
  end

  def about
	end

	def contact
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.slim
- provide(:title,"About")
h1
  | About
p
  a[href="https://railstutorial.jp/"]
    | Ruby on Rails Tutorial
  |  is a 
  a[href="https://railstutorial.jp/#ebook"]
    | book
  |  and 
  a[href="https://railstutorial.jp/#screencast"]
    | screencast
  |  to teach web development with 
  a[href="http://rubyonrails.org/"]
    | Ruby on Rails
  | . This is the sample application for the tutorial. 

app/views/static_pages/contact.html.slim
- provide(:title, "Contact")
h1
	| Contact
p
	| Contact the Ruby on Rails Tutorial about the sample app at the
	a[href="https://railstutorial.jp/contact"]
  	| contact page.

app/views/static_pages/help.html.slim
- provide(:title, "Help") 
h1
  | Help
p
  |  Get help on the Ruby on Rails Tutorial at the 
  a[href="https://railstutorial.jp/help"]
    | Rails Tutorial help page
  | . To get help on this sample app, see the 
  a[href="https://railstutorial.jp/#ebook"]
    em
      | Ruby on Rails Tutorial
    |  book
  | . 

app/views/static_pages/home.html.slim
- provide(:title, "Home")

- if logged_in?
  div.row
    aside.col-md-4
      section.user_info
        =render 'shared/user_info'
      section.stats
        =render 'shared/stats'
      section.micropost_form
        =render 'shared/micropost_form'
    div.col-md-8
      h3
        |Micropost Feed
      =render 'shared/feed'
-else
  div.center.jumbotron
    h1
      | Welcome to the Sample App

    h2
      | This is the home page for the
      a[href="https://railstutorial.jp/"]
        | Ruby on Rails Tutorial
      | sample application.

    = link_to signup_path , class: "btn btn-lg btn-primary"
      | Sign up now!

= link_to 'http://rubyonrails.org/'
  = image_tag "rails.png", alt: "Rails logo"
  /= image_tag "kitten.jpg", alt: "koneko"