config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy' 

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

	root to: 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update], param: :reset_token
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.slim
- if object.errors.any?
	#error_explanation
	  .alert.alert-danger
	    |  The form contains 
	    = pluralize(object.errors.count, "error")
	    | . 
	  ul
	    - object.errors.full_messages.each do |msg|
	      li
	        = msg

app/views/shared/_feed.html.slim
- if @feed_items.any?
	ol.microposts
		= render @feed_items

	= will_paginate @feed_items

app/views/shared/_micropost_form.html.slim
= form_with model: @micropost , local: true do |f|
	=render 'shared/error_messages', locals: {micropost: @micropost}, object: f.object
	div.field
		=f.text_area :content, id: :content, placeholder: "Compose new micropost..."
	=f.submit "Post", class: "btn btn-primary", id: :submit

	span.picture
		=f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'

	javascript:
		$('#micropost_picture').bind('change',function(){
			var size_in_megabytes = this.files[0].size/1024/1024;
			if(size_in_megabytes > 5){
				alert('Maximum file size is 5MB. Please choose a smaller file.')
			}
		});

app/views/shared/_stats.html.slim
- @user ||= current_user
div.stats
	a[href="#{following_user_path(@user)}"]
		strong#folowing.stat
			= @user.following.count
		|following

	a[href="#{followers_user_path(@user)}"]
		strong#folowers.stat
			= @user.followers.count
		|followers

app/views/shared/_user_info.html.slim
=link_to gravatar_for(current_user,size: 50), current_user
h1
	=current_user.name
span
	=link_to "view my profile", current_user
span
	= pluralize(current_user.microposts.count,"micropost")