config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy' 

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

	root to: 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update], param: :reset_token
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.slim
footer.footer
  small
    | The 
    a[href="https://railstutorial.jp/"]
      | Ruby on Rails Tutorial 
    |by 
    a[href="http://www.michaelhartl.com/"]
      | Michael Hartl

  nav
    ul
      li
        = link_to about_path
          | About   
      li
        = link_to contact_path
          | Contact
      li
        a[href="http://news.railstutorial.org/"]
          | News

app/views/layouts/_head.html.slim
= csrf_meta_tags
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  div.container
    = link_to "sample app", root_path , id: "logo"
    nav
      ul.nav.navbar-nav.navbar-right
        li
          = link_to "Home",   root_path
        li
          = link_to "Help",   help_path
        - if logged_in?
          li
            = link_to "Users" , users_path
          li.dropdown
            a href='#' class="dropdown-toggle" data-toggle="dropdown" 
              | Account 
              b.caret
            ul.dropdown-menu
              li
                = link_to "Profile", current_user
              li
                = link_to "Settings", edit_user_path(current_user)
              li.divider
              li
                = link_to "Log out", logout_path , method: :delete
        - else
          li
            = link_to "Log in", login_path

app/views/layouts/_shim.html.slim
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:title))
    = render 'layouts/head'
    = render 'layouts/shim'
  body
    = render 'layouts/header'
    div.container
      - flash.each do |message_type,message|
        =content_tag(:div,message,class:"alert alert-#{message_type}")
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?